### ISSUE TITLE
"Rewrap text" is useless

### ISSUE THREAD

**Issue by rossburton** [savoirfairelinux/vscode-bitbake#14]
The "rewrap text" command is basically pointless in bitbake mode.

Paste the following into a recipe or other file in BitBake mode:

```
FOO = "foo"
# The following list provides some explanation for the statements found in the example reference machine configuration file for the BeagleBone development boards.
BAR = "bar"
```

Move the cursor to the comment line and press 'Rewrap Comment/Text", you'll get this:

```
FOO = "foo" # The following list provides some explanation for the statements
found in the example reference machine configuration file for the BeagleBone
development boards. BAR = "bar"
```

That is not useful. Repeating the same test in 'Shell Script' mode produces the expected output:

```
FOO = "foo"
# The following list provides some explanation for the statements found in the
# example reference machine configuration file for the BeagleBone development
# boards.
BAR = "bar"
```

**Comment by deribaucourt** [comment]
Hello, thanks for reporting this issue. I could indeed reproduce it with the current marketplace version but this seems to have been fixed if you use the staging branch.

Could you try this again with the staging version and confirm if this fixes your problem?

**Comment by rossburton** [comment]
Sorry, still broken with the vsix I just grabbed from github.

**Comment by deribaucourt** [comment]
Rewrapping is handled by an external extension. On my setup I'm using stkb.rewrap version 1.16.3.

Could you please share with us the logs from this command, which prints out the list of extensions you have installed:
`code --show-versions --list-extensions`

With my rewrap extension, The option "Rewrap Comment/Text" is part of the command prompt (ctrl+shift+p). I do not have it in the contextual menu. Maybe you have a different extension than me?

Additionally, please send us your Rewrap extension's settings. From the extension panel, right click the extension, then "Extension Settings". A screenshot of the User and Workspace settings would do. I'm using the default settings.

![image](https://github.com/savoirfairelinux/vscode-bitbake/assets/19970889/3721529f-4588-4095-abc2-de2642148d49)

**Comment by rossburton** [comment]
Confirmed that I have `stkb.rewrap@1.16.3` installed, the rewrap settings are the same, and I'm running _Rewrap Comment/Text_ from the command prompt.

I'd actually forgotten that was a separate plugin, not integrated into vscode.  I've uninstalled the old bitbake plugin and am using a vsix from github as of last week.

From my very bad knowledge of VS Code and every less F#, it looks like `client/language-configuration.json` should have `block` and/or `line` attributes, telling the reformat plugin that `#` is the comment character.

**Comment by deribaucourt** [comment]
An idea came to me. When you installed the .vsix from github, did you first uninstall the market place one? Because they have different identities for now, they will conflict if both are installed at the same time. So maybe you keep observing the behavior of the previous version.
